baseURL = "https://patlau.github.io"
languageCode = "en-us"
title = "Lauper"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Patrick Lauper"
    description = "Information Technology Consulting"
    githubUsername = "patlau"
    accent = ""
    showBorder = true
    backgroundColor = ""
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["java", "xml"]
    profilePic = ""
    css = ["css/custom.css"]
    js = ["https://kit.fontawesome.com/141a99f265.js"]

[menu]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:p.lauper@yahoo.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://wa.me/41792152002"
    name = "whatsapp"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/company/lauper-it-consulting"
    name = "linkedin"
    weight = 2

