baseURL = "https://patlau.gitlab.io"
languageCode = "en-us"
title = "Lauper"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Patrick Lauper"
    description = "Lauper Information Technology Consulting"
    githubUsername = "patlau"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:info@lauper-it-consulting.ch"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/patrick-lauper-42110277/"
    name = "linkedin"
    weight = 2

