baseURL = "https://www.lauper-it-consulting.ch"
languageCode = "en-us"
title = "Lauper"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Patrick Lauper"
    description = "Information Technology Consulting"
    githubUsername = "patlau"
    accent = ""
    showBorder = true
    backgroundColor = ""
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["java", "xml"]
    profilePic = ""
    css = ["css/custom.css"]
    js = ["https://kit.fontawesome.com/141a99f265.js"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/inno"
    name = "Innovation"
    weight = 2

[[menu.main]]
    url = "/projects"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/links"
    name = "Links"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:p.lauper@yahoo.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://www.linkedin.com/in/patrick-lauper-42110277/"
    name = "linkedin"
    weight = 2
 